version: '3'
services:
  portainer:
    env_file: .env
    image: portainer/portainer-ce
    container_name: portainer
    restart: unless-stopped
    volumes:
      - ~/portainer:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "9443:9443"
    network_mode: "bridge"
    security_opt:
      - no-new-privileges:true
    healthcheck:
      interval: "2s"
      retries: 10
      test: [ "CMD", "curl", "-f", "https://${DOMAIN}/portainer" ]
      timeout: "1s"
      start_period: "5s"
