version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts-alpine-jdk17
    container_name: jenkins
    restart: unless-stopped
    network_mode: bridge
    user: "jenkins:jenkins"
    ports:
      - "18080:8080"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /pvs/jenkins/jenkins_home:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro