version: "3"
services:
  jenkins:
    image: jenkins/jenkins:lts-alpine-jdk17
    container_name: jenkins
    restart: unless-stopped
    network_mode: bridge
    environment:
      - JENKINS_OPTS=--httpPort=-1 --httpsPort=8083 --httpsKeyStore=/var/lib/jenkins/cert.jks --httpsKeyStorePassword=${KEYSTORE_PASSWORD}
    ports:
      - "18083:8083"
    security_opt:
      - no-new-privileges:true
    volumes:
      - /pvs/jenkins/home:/var/jenkins_home:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/certificates/cert.jks:/var/lib/jenkins/cert.jks:ro