version: "3"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    restart: unless-stopped
    network_mode: bridge
    ports:
      - 8096:8096
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Hong_Kong
    volumes:
      - /DATA/media/movies:/movies:ro
      - /DATA/media/tv:/tv:ro
      - /pvs/jellyfin/config:/config
      - /pvs/jellyfin/cache:/cache
    devices:
      - /dev/dri:/dev/dri